# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_field_1_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Added field 1 label'),
        ),
        migrations.AddField(
            model_name='item',
            name='added_field_1_label_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Added field 1 label'),
        ),
        migrations.AddField(
            model_name='item',
            name='added_field_1_label_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Added field 1 label'),
        ),
        migrations.AddField(
            model_name='item',
            name='added_field_1_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Added field 1 value'),
        ),
        migrations.AddField(
            model_name='item',
            name='added_field_1_value_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Added field 1 value'),
        ),
        migrations.AddField(
            model_name='item',
            name='added_field_1_value_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Added field 1 value'),
        ),
        migrations.AddField(
            model_name='item',
            name='added_field_2_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Added field 2 label'),
        ),
        migrations.AddField(
            model_name='item',
            name='added_field_2_label_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Added field 2 label'),
        ),
        migrations.AddField(
            model_name='item',
            name='added_field_2_label_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Added field 2 label'),
        ),
        migrations.AddField(
            model_name='item',
            name='added_field_2_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Added field 2 value'),
        ),
        migrations.AddField(
            model_name='item',
            name='added_field_2_value_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Added field 2 value'),
        ),
        migrations.AddField(
            model_name='item',
            name='added_field_2_value_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Added field 2 value'),
        ),
        migrations.AddField(
            model_name='item',
            name='added_field_3_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Added field 3 label'),
        ),
        migrations.AddField(
            model_name='item',
            name='added_field_3_label_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Added field 3 label'),
        ),
        migrations.AddField(
            model_name='item',
            name='added_field_3_label_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Added field 3 label'),
        ),
        migrations.AddField(
            model_name='item',
            name='added_field_3_value',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Added field 3 value'),
        ),
        migrations.AddField(
            model_name='item',
            name='added_field_3_value_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Added field 3 value'),
        ),
        migrations.AddField(
            model_name='item',
            name='added_field_3_value_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Added field 3 value'),
        ),
        migrations.AddField(
            model_name='item',
            name='annual_income',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Annual income ($)'),
        ),
        migrations.AddField(
            model_name='item',
            name='apartments_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Apartments number'),
        ),
        migrations.AddField(
            model_name='item',
            name='ccd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ccd (CCD)'),
        ),
        migrations.AddField(
            model_name='item',
            name='cost_per_housing',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cost per housing (CPH) ($)'),
        ),
        migrations.AddField(
            model_name='item',
            name='down_payment_required',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Down payment required ($)'),
        ),
        migrations.AddField(
            model_name='item',
            name='economic_value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Economic_value ($)'),
        ),
        migrations.AddField(
            model_name='item',
            name='gross_revenue_multiplier',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Gross revenue multiplier (GRM)'),
        ),
        migrations.AddField(
            model_name='item',
            name='housing_descriptions',
            field=models.CharField(blank=True, max_length=1020, null=True, verbose_name='Housing descriptions'),
        ),
        migrations.AddField(
            model_name='item',
            name='housing_descriptions_en',
            field=models.CharField(blank=True, max_length=1020, null=True, verbose_name='Housing descriptions'),
        ),
        migrations.AddField(
            model_name='item',
            name='housing_descriptions_fr',
            field=models.CharField(blank=True, max_length=1020, null=True, verbose_name='Housing descriptions'),
        ),
        migrations.AddField(
            model_name='item',
            name='maximum_loan',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum loan (%)'),
        ),
        migrations.AddField(
            model_name='item',
            name='net_income_multiplier',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Net income multiplier (NIM)'),
        ),
        migrations.AddField(
            model_name='item',
            name='overall_rate_update',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Overall rate of update (ORU) (%)'),
        ),
    ]
