# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20191117_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='annual_income',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='Annual income ($)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost_per_housing',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='Cost per housing (CPH) ($)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='down_payment_required',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='Down payment required ($)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='economic_value',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=9, null=True, verbose_name='Economic value ($)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='maximum_loan',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Maximum loan (%)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=9, verbose_name='Price'),
        ),
    ]
