# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20191117_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='property_type',
            field=models.CharField(choices=[('', 'Select property type'), ('apartment', 'Apartment'), ('duplex', 'Duplex'), ('quadruplex', 'Quadruplex'), ('quintuplex', 'Quintuplex'), ('multiple_housing', 'Multiple housing'), ('ground_floor_house', 'Ground floor house'), ('two_or_more_storey', 'Two or more storey'), ('split_level', 'Split-level'), ('one_and_a_half_storey_house', 'One-and-a-half-storey house'), ('mobile_home', 'Mobile home'), ('house', 'House'), ('loft_studio', 'Loft / Studio'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('company', 'Company (business)'), ('bulk', 'Bulk (block sale)'), ('land', 'Land'), ('lot', 'Lot'), ('farm', 'Farm'), ('hobby_farm', 'Hobby farm'), ('other', 'Other')], default='', max_length=50, verbose_name='Property type'),
        ),
    ]
