# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-11 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=100, verbose_name='City label')),
                ('city_val', models.CharField(blank=True, default='', max_length=100, verbose_name='City')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('initials_bg_color', models.CharField(default='#ffffff', max_length=10, verbose_name='Initials background color')),
                ('initials_color', models.CharField(default='#000000', max_length=10, verbose_name='Initials color')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('testimonial', models.TextField(verbose_name='Testimonial')),
            ],
            options={
                'db_table': 'testimonial',
            },
        ),
    ]
