# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_auto_20191112_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='testimonial_en',
            field=models.TextField(null=True, verbose_name='Testimonial'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='testimonial_fr',
            field=models.TextField(null=True, verbose_name='Testimonial'),
        ),
    ]
