# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-28 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('last_name', models.CharField(max_length=30, verbose_name='First name')),
            ],
            options={
                'db_table': 'newsletter',
            },
        ),
    ]
