# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20191117_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbuy',
            name='lot_size_max',
            field=models.PositiveIntegerField(default=0, verbose_name='Property size max(m²)'),
        ),
        migrations.AlterField(
            model_name='contactbuy',
            name='lot_size_min',
            field=models.PositiveIntegerField(default=0, verbose_name='Property size min(m²)'),
        ),
    ]
