# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_auto_20191117_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funding',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='description_fr',
        ),
    ]
