# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-01 17:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_auto_20191201_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='funding.Bank'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funding',
            name='user_email',
            field=models.EmailField(default='test@yopmail.com', max_length=255, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
