# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0004_auto_20191117_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='first_name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='funding',
            name='first_name_fr',
            field=models.CharField(max_length=30, null=True, verbose_name='First name'),
        ),
    ]
