# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0006_auto_20191117_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='description2',
            field=models.TextField(default='225', verbose_name='Description2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funding',
            name='description2_en',
            field=models.TextField(null=True, verbose_name='Description2'),
        ),
        migrations.AddField(
            model_name='funding',
            name='description2_fr',
            field=models.TextField(null=True, verbose_name='Description2'),
        ),
    ]
