# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0007_auto_20191117_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funding',
            name='description2',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='description2_en',
        ),
        migrations.RemoveField(
            model_name='funding',
            name='description2_fr',
        ),
    ]
