# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-22 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0009_auto_20191122_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fundings', to='funding.Bank'),
        ),
        migrations.AlterField(
            model_name='funding',
            name='user_email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
    ]
