# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-11 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_icon', models.CharField(choices=[('', 'Select'), ('facebook', 'Facebook'), ('google-plus', 'G+'), ('instagram', 'Instagram'), ('linkedin', 'Linkedin'), ('twitter', 'Twitter'), ('youtube', 'Youtube')], default='', max_length=20, verbose_name='Fa icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('label', models.CharField(max_length=30, verbose_name='Label')),
                ('url', models.CharField(default='', max_length=120, verbose_name='Url')),
            ],
            options={
                'db_table': 'social_link',
            },
        ),
    ]
