# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-28 15:50
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutedBackup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('is_automatically', models.BooleanField(default=True, verbose_name='Is automatically')),
            ],
            options={
                'db_table': 'executed_backup',
            },
        ),
        migrations.CreateModel(
            name='SettingsDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(blank=True, help_text='Header image', null=True, upload_to='dev/images/settings_db/header')),
                ('header_background_image', models.ImageField(blank=True, help_text='Header background image', null=True, upload_to='dev/images/settings_db/header')),
                ('header_text_color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Header text color')),
                ('logo', models.ImageField(blank=True, help_text='Logo image', null=True, upload_to='dev/images/settings_db/header')),
                ('main_bg_image', models.ImageField(blank=True, help_text='Body background image', null=True, upload_to='dev/images/settings_db/header')),
                ('site_name', models.CharField(max_length=255, verbose_name='Site name')),
                ('home_page_title_1', models.CharField(max_length=765, verbose_name='Title line 1')),
                ('home_page_title_1_en', models.CharField(max_length=765, null=True, verbose_name='Title line 1')),
                ('home_page_title_1_fr', models.CharField(max_length=765, null=True, verbose_name='Title line 1')),
                ('home_page_title_2', models.CharField(blank=True, max_length=765, null=True, verbose_name='Title line 2')),
                ('home_page_title_2_en', models.CharField(blank=True, max_length=765, null=True, verbose_name='Title line 2')),
                ('home_page_title_2_fr', models.CharField(blank=True, max_length=765, null=True, verbose_name='Title line 2')),
                ('home_page_row_1_title', models.CharField(blank=True, max_length=510, null=True, verbose_name='Row 1 title')),
                ('home_page_row_1_title_en', models.CharField(blank=True, max_length=510, null=True, verbose_name='Row 1 title')),
                ('home_page_row_1_title_fr', models.CharField(blank=True, max_length=510, null=True, verbose_name='Row 1 title')),
                ('home_page_row_1_p_1', models.TextField(blank=True, null=True, verbose_name='Row 1 paragraph 1')),
                ('home_page_row_1_p_1_en', models.TextField(blank=True, null=True, verbose_name='Row 1 paragraph 1')),
                ('home_page_row_1_p_1_fr', models.TextField(blank=True, null=True, verbose_name='Row 1 paragraph 1')),
                ('home_page_row_1_p_2', models.TextField(blank=True, null=True, verbose_name='Row 1 paragraph 2')),
                ('home_page_row_1_p_2_en', models.TextField(blank=True, null=True, verbose_name='Row 1 paragraph 2')),
                ('home_page_row_1_p_2_fr', models.TextField(blank=True, null=True, verbose_name='Row 1 paragraph 2')),
                ('home_page_row_1_p_3', models.TextField(blank=True, null=True, verbose_name='Row 1 paragraph 3')),
                ('home_page_row_1_p_3_en', models.TextField(blank=True, null=True, verbose_name='Row 1 paragraph 3')),
                ('home_page_row_1_p_3_fr', models.TextField(blank=True, null=True, verbose_name='Row 1 paragraph 3')),
                ('home_page_row_2_title', models.CharField(blank=True, max_length=510, null=True, verbose_name='Row 2 title')),
                ('home_page_row_2_title_en', models.CharField(blank=True, max_length=510, null=True, verbose_name='Row 2 title')),
                ('home_page_row_2_title_fr', models.CharField(blank=True, max_length=510, null=True, verbose_name='Row 2 title')),
                ('home_page_row_2_p_1', models.TextField(blank=True, null=True, verbose_name='Row 2 paragraph 1')),
                ('home_page_row_2_p_1_en', models.TextField(blank=True, null=True, verbose_name='Row 2 paragraph 1')),
                ('home_page_row_2_p_1_fr', models.TextField(blank=True, null=True, verbose_name='Row 2 paragraph 1')),
                ('home_page_row_2_p_2', models.TextField(blank=True, null=True, verbose_name='Row 2 paragraph 2')),
                ('home_page_row_2_p_2_en', models.TextField(blank=True, null=True, verbose_name='Row 2 paragraph 2')),
                ('home_page_row_2_p_2_fr', models.TextField(blank=True, null=True, verbose_name='Row 2 paragraph 2')),
                ('home_page_row_2_p_3', models.TextField(blank=True, null=True, verbose_name='Row 2 paragraph 3')),
                ('home_page_row_2_p_3_en', models.TextField(blank=True, null=True, verbose_name='Row 2 paragraph 3')),
                ('home_page_row_2_p_3_fr', models.TextField(blank=True, null=True, verbose_name='Row 2 paragraph 3')),
                ('home_page_row_3_title', models.CharField(blank=True, max_length=510, null=True, verbose_name='Row 3 title')),
                ('home_page_row_3_title_en', models.CharField(blank=True, max_length=510, null=True, verbose_name='Row 3 title')),
                ('home_page_row_3_title_fr', models.CharField(blank=True, max_length=510, null=True, verbose_name='Row 3 title')),
                ('home_page_row_3_p_1', models.TextField(blank=True, null=True, verbose_name='Row 3 paragraph 1')),
                ('home_page_row_3_p_1_en', models.TextField(blank=True, null=True, verbose_name='Row 3 paragraph 1')),
                ('home_page_row_3_p_1_fr', models.TextField(blank=True, null=True, verbose_name='Row 3 paragraph 1')),
                ('home_page_row_3_p_2', models.TextField(blank=True, null=True, verbose_name='Row 3 paragraph 2')),
                ('home_page_row_3_p_2_en', models.TextField(blank=True, null=True, verbose_name='Row 3 paragraph 2')),
                ('home_page_row_3_p_2_fr', models.TextField(blank=True, null=True, verbose_name='Row 3 paragraph 2')),
                ('home_page_row_3_p_3', models.TextField(blank=True, null=True, verbose_name='Row 3 paragraph 3')),
                ('home_page_row_3_p_3_en', models.TextField(blank=True, null=True, verbose_name='Row 3 paragraph 3')),
                ('home_page_row_3_p_3_fr', models.TextField(blank=True, null=True, verbose_name='Row 3 paragraph 3')),
            ],
            options={
                'db_table': 'settings_db',
            },
        ),
    ]
