# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-14 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsDb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_bg', models.ImageField(help_text='Header background image', upload_to='images/settings_db/header')),
                ('logo', models.ImageField(help_text='Logo image', upload_to='images/settings_db/header')),
                ('site_name', models.CharField(max_length=255, verbose_name='Site name')),
                ('home_page_title_1', models.CharField(max_length=765, verbose_name='Title line 1')),
                ('home_page_title_1_en', models.CharField(max_length=765, null=True, verbose_name='Title line 1')),
                ('home_page_title_1_fr', models.CharField(max_length=765, null=True, verbose_name='Title line 1')),
                ('home_page_title_2', models.CharField(blank=True, max_length=765, null=True, verbose_name='Title line 2')),
                ('home_page_title_2_en', models.CharField(blank=True, max_length=765, null=True, verbose_name='Title line 2')),
                ('home_page_title_2_fr', models.CharField(blank=True, max_length=765, null=True, verbose_name='Title line 2')),
                ('home_page_left_column_title', models.CharField(blank=True, max_length=510, null=True, verbose_name='Left column title')),
                ('home_page_left_column_title_en', models.CharField(blank=True, max_length=510, null=True, verbose_name='Left column title')),
                ('home_page_left_column_title_fr', models.CharField(blank=True, max_length=510, null=True, verbose_name='Left column title')),
                ('home_page_left_column_p_1', models.TextField(blank=True, null=True, verbose_name='Left column paragraph 1')),
                ('home_page_left_column_p_1_en', models.TextField(blank=True, null=True, verbose_name='Left column paragraph 1')),
                ('home_page_left_column_p_1_fr', models.TextField(blank=True, null=True, verbose_name='Left column paragraph 1')),
                ('home_page_left_column_p_2', models.TextField(blank=True, null=True, verbose_name='Left column paragraph 2')),
                ('home_page_left_column_p_2_en', models.TextField(blank=True, null=True, verbose_name='Left column paragraph 2')),
                ('home_page_left_column_p_2_fr', models.TextField(blank=True, null=True, verbose_name='Left column paragraph 2')),
                ('home_page_left_column_p_3', models.TextField(blank=True, null=True, verbose_name='Left column paragraph 3')),
                ('home_page_left_column_p_3_en', models.TextField(blank=True, null=True, verbose_name='Left column paragraph 3')),
                ('home_page_left_column_p_3_fr', models.TextField(blank=True, null=True, verbose_name='Left column paragraph 3')),
                ('home_page_right_column_title', models.CharField(blank=True, max_length=510, null=True, verbose_name='Right column title')),
                ('home_page_right_column_title_en', models.CharField(blank=True, max_length=510, null=True, verbose_name='Right column title')),
                ('home_page_right_column_title_fr', models.CharField(blank=True, max_length=510, null=True, verbose_name='Right column title')),
                ('home_page_right_column_p_1', models.TextField(blank=True, null=True, verbose_name='Right column paragraph 1')),
                ('home_page_right_column_p_1_en', models.TextField(blank=True, null=True, verbose_name='Right column paragraph 1')),
                ('home_page_right_column_p_1_fr', models.TextField(blank=True, null=True, verbose_name='Right column paragraph 1')),
                ('home_page_right_column_p_2', models.TextField(blank=True, null=True, verbose_name='Right column paragraph 2')),
                ('home_page_right_column_p_2_en', models.TextField(blank=True, null=True, verbose_name='Right column paragraph 2')),
                ('home_page_right_column_p_2_fr', models.TextField(blank=True, null=True, verbose_name='Right column paragraph 2')),
                ('home_page_right_column_p_3', models.TextField(blank=True, null=True, verbose_name='Right column paragraph 3')),
                ('home_page_right_column_p_3_en', models.TextField(blank=True, null=True, verbose_name='Right column paragraph 3')),
                ('home_page_right_column_p_3_fr', models.TextField(blank=True, null=True, verbose_name='Right column paragraph 3')),
                ('home_page_row_1_title', models.CharField(blank=True, max_length=510, null=True, verbose_name='Row 1 title')),
                ('home_page_row_1_title_en', models.CharField(blank=True, max_length=510, null=True, verbose_name='Row 1 title')),
                ('home_page_row_1_title_fr', models.CharField(blank=True, max_length=510, null=True, verbose_name='Row 1 title')),
                ('home_page_row_1_p_1', models.TextField(blank=True, null=True, verbose_name='Row 1 paragraph 1')),
                ('home_page_row_1_p_1_en', models.TextField(blank=True, null=True, verbose_name='Row 1 paragraph 1')),
                ('home_page_row_1_p_1_fr', models.TextField(blank=True, null=True, verbose_name='Row 1 paragraph 1')),
                ('home_page_row_1_p_2', models.TextField(blank=True, null=True, verbose_name='Row 1 paragraph 2')),
                ('home_page_row_1_p_2_en', models.TextField(blank=True, null=True, verbose_name='Row 1 paragraph 2')),
                ('home_page_row_1_p_2_fr', models.TextField(blank=True, null=True, verbose_name='Row 1 paragraph 2')),
                ('home_page_row_1_p_3', models.TextField(blank=True, null=True, verbose_name='Row 1 paragraph 3')),
                ('home_page_row_1_p_3_en', models.TextField(blank=True, null=True, verbose_name='Row 1 paragraph 3')),
                ('home_page_row_1_p_3_fr', models.TextField(blank=True, null=True, verbose_name='Row 1 paragraph 3')),
                ('home_page_row_2_title', models.CharField(blank=True, max_length=510, null=True, verbose_name='Row 2 title')),
                ('home_page_row_2_title_en', models.CharField(blank=True, max_length=510, null=True, verbose_name='Row 2 title')),
                ('home_page_row_2_title_fr', models.CharField(blank=True, max_length=510, null=True, verbose_name='Row 2 title')),
                ('home_page_row_2_p_1', models.TextField(blank=True, null=True, verbose_name='Row 2 paragraph 1')),
                ('home_page_row_2_p_1_en', models.TextField(blank=True, null=True, verbose_name='Row 2 paragraph 1')),
                ('home_page_row_2_p_1_fr', models.TextField(blank=True, null=True, verbose_name='Row 2 paragraph 1')),
                ('home_page_row_2_p_2', models.TextField(blank=True, null=True, verbose_name='Row 2 paragraph 2')),
                ('home_page_row_2_p_2_en', models.TextField(blank=True, null=True, verbose_name='Row 2 paragraph 2')),
                ('home_page_row_2_p_2_fr', models.TextField(blank=True, null=True, verbose_name='Row 2 paragraph 2')),
                ('home_page_row_2_p_3', models.TextField(blank=True, null=True, verbose_name='Row 2 paragraph 3')),
                ('home_page_row_2_p_3_en', models.TextField(blank=True, null=True, verbose_name='Row 2 paragraph 3')),
                ('home_page_row_2_p_3_fr', models.TextField(blank=True, null=True, verbose_name='Row 2 paragraph 3')),
            ],
            options={
                'db_table': 'settings_db',
            },
        ),
    ]
