# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-16 21:43
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_left_column_p_1',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_left_column_p_1_en',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_left_column_p_1_fr',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_left_column_p_2',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_left_column_p_2_en',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_left_column_p_2_fr',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_left_column_p_3',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_left_column_p_3_en',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_left_column_p_3_fr',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_left_column_title',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_left_column_title_en',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_left_column_title_fr',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_right_column_p_1',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_right_column_p_1_en',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_right_column_p_1_fr',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_right_column_p_2',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_right_column_p_2_en',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_right_column_p_2_fr',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_right_column_p_3',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_right_column_p_3_en',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_right_column_p_3_fr',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_right_column_title',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_right_column_title_en',
        ),
        migrations.RemoveField(
            model_name='settingsdb',
            name='home_page_right_column_title_fr',
        ),
        migrations.AddField(
            model_name='settingsdb',
            name='header_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Header text color'),
        ),
        migrations.AddField(
            model_name='settingsdb',
            name='home_page_row_3_p_1',
            field=models.TextField(blank=True, null=True, verbose_name='Row 3 paragraph 1'),
        ),
        migrations.AddField(
            model_name='settingsdb',
            name='home_page_row_3_p_1_en',
            field=models.TextField(blank=True, null=True, verbose_name='Row 3 paragraph 1'),
        ),
        migrations.AddField(
            model_name='settingsdb',
            name='home_page_row_3_p_1_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Row 3 paragraph 1'),
        ),
        migrations.AddField(
            model_name='settingsdb',
            name='home_page_row_3_p_2',
            field=models.TextField(blank=True, null=True, verbose_name='Row 3 paragraph 2'),
        ),
        migrations.AddField(
            model_name='settingsdb',
            name='home_page_row_3_p_2_en',
            field=models.TextField(blank=True, null=True, verbose_name='Row 3 paragraph 2'),
        ),
        migrations.AddField(
            model_name='settingsdb',
            name='home_page_row_3_p_2_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Row 3 paragraph 2'),
        ),
        migrations.AddField(
            model_name='settingsdb',
            name='home_page_row_3_p_3',
            field=models.TextField(blank=True, null=True, verbose_name='Row 3 paragraph 3'),
        ),
        migrations.AddField(
            model_name='settingsdb',
            name='home_page_row_3_p_3_en',
            field=models.TextField(blank=True, null=True, verbose_name='Row 3 paragraph 3'),
        ),
        migrations.AddField(
            model_name='settingsdb',
            name='home_page_row_3_p_3_fr',
            field=models.TextField(blank=True, null=True, verbose_name='Row 3 paragraph 3'),
        ),
        migrations.AddField(
            model_name='settingsdb',
            name='home_page_row_3_title',
            field=models.CharField(blank=True, max_length=510, null=True, verbose_name='Row 3 title'),
        ),
        migrations.AddField(
            model_name='settingsdb',
            name='home_page_row_3_title_en',
            field=models.CharField(blank=True, max_length=510, null=True, verbose_name='Row 3 title'),
        ),
        migrations.AddField(
            model_name='settingsdb',
            name='home_page_row_3_title_fr',
            field=models.CharField(blank=True, max_length=510, null=True, verbose_name='Row 3 title'),
        ),
        migrations.AddField(
            model_name='settingsdb',
            name='main_bg_image',
            field=models.ImageField(default='', help_text='Body background image', upload_to='images/settings_db/header'),
        ),
    ]
