# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-16 18:39
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsdb',
            name='header_text_color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Header text color'),
        ),
    ]
