# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-18 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_db', '0002_auto_20191116_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settingsdb',
            name='header_bg',
        ),
        migrations.AddField(
            model_name='settingsdb',
            name='header_background_image',
            field=models.ImageField(blank=True, help_text='Header background image', null=True, upload_to='images/settings_db/header'),
        ),
        migrations.AddField(
            model_name='settingsdb',
            name='header_image',
            field=models.ImageField(blank=True, help_text='Header image', null=True, upload_to='images/settings_db/header'),
        ),
        migrations.AlterField(
            model_name='settingsdb',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo image', null=True, upload_to='images/settings_db/header'),
        ),
        migrations.AlterField(
            model_name='settingsdb',
            name='main_bg_image',
            field=models.ImageField(blank=True, help_text='Body background image', null=True, upload_to='images/settings_db/header'),
        ),
    ]
