# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_db', '0003_auto_20191116_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsdb',
            name='header_background_image',
            field=models.ImageField(help_text='Header background image', null=True, upload_to='images/settings_db/header'),
        ),
        migrations.AlterField(
            model_name='settingsdb',
            name='header_bg',
            field=models.ImageField(help_text='Header image', upload_to='images/settings_db/header'),
        ),
    ]
