# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_db', '0004_auto_20191117_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settingsdb',
            old_name='header_bg',
            new_name='header_image',
        ),
    ]
