# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-17 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_db', '0007_auto_20191117_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsdb',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo image', null=True, upload_to='images/settings_db/header'),
        ),
    ]
