# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-28 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=510, verbose_name='Address')),
                ('address_en', models.CharField(max_length=510, null=True, verbose_name='Address')),
                ('address_fr', models.CharField(max_length=510, null=True, verbose_name='Address')),
                ('agency_name', models.CharField(max_length=255, verbose_name='Agency name')),
                ('email', models.CharField(default='Jalil.elmahboubi@gmail.com', max_length=255, verbose_name='Email')),
                ('enable_map', models.BooleanField(default=True, verbose_name='Enable map')),
                ('fax', models.CharField(default='450 462 1509', max_length=255, verbose_name='Fax')),
                ('full_name', models.CharField(default='ELMAHBOUBI Abdjalil', max_length=255, verbose_name='Full name')),
                ('gps_latitude', models.FloatField(blank=True, default=45.474459, null=True, verbose_name='GPS Latitude')),
                ('gps_longitude', models.FloatField(blank=True, default=-73.470234, null=True, verbose_name='GPS Longitude')),
                ('image', models.ImageField(help_text="Admin's image", upload_to='dev/images/admin_data')),
                ('tel', models.CharField(default='514 967 3743', max_length=255, verbose_name='Telephone')),
            ],
            options={
                'db_table': 'admin_data',
            },
        ),
    ]
