# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-16 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindata',
            name='agency_name',
            field=models.CharField(max_length=255, verbose_name='Royal Le page Triomphe'),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='fax',
            field=models.CharField(default='450 462 1509', max_length=255, verbose_name='Fax'),
        ),
        migrations.AlterField(
            model_name='admindata',
            name='tel',
            field=models.CharField(default='514 967 3743', max_length=255, verbose_name='Telephone'),
        ),
    ]
